quarkus:
  application:
    name: {project.name}
    version: {project.version}

  http:
    port: 8848
    root-path: /api/v1
    non-application-root-path: /dev

  jackson:
    timezone: PRC

  banner:
    path: banner.txt

  profile: dev
  default-locale: zh_CN

  swagger-ui:
    path: /api-doc
    always-include: true

  smallrye-openapi:
    path: /openapi
    info-title: {project.name}
    info-version: {project.version}
    info-contact-name: fordes123
    info-contact-url: https://fordes.dev
    info-license-name: AGPLv3
    info-license-url: https://www.gnu.org/licenses/agpl-3.0.en.html

  log:
    level: INFO
    file:
      path: logs/iptv-subscriber.log
      level: WARN
      encoding: UTF-8
    console:
      level: DEBUG
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
    category:
      "dev.fordes.iptv":
        level: DEBUG

#iptv-subscriber:
#  debug: true