server:
  log-level: DEBUG

tv-source:
  supplier:
    - E:\test.m3u8
  #    - https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8
  consumer:
    - file: E:\\cctv-ipv4.m3u
      filter:
        - dpi:480